¡Hola Israel! Como te va?

Mi nombre es Facundo Lozano! Un gusto conocerte, seré tu revisor en este proyecto.

A continuación un poco sobre la modalidad de revisión que usaremos:

Cuando enccuentro un error por primera vez, simplemente lo señalaré, te dejaré encontrarlo y arreglarlo tú cuenta. Además, a lo largo del texto iré haciendo algunas observaciones sobre mejora en tu código y también haré comentarios sobre tus percepciones sobre el tema. Pero si aún no puedes realizar esta tarea, te daré una pista más precisa en la próxima iteración y también algunos ejemplos prácticos. Estaré abierto a comentarios y discusiones sobre el tema.

Encontrará mis comentarios a continuación: **no los mueva, modifique ni elimine**.

Puedes encontrar mis comentarios en cuadros verdes, amarillos o rojos como este:

<div class="alert alert-block alert-success">
<b>Comentario del revisor.</b> <a class="tocSkip"></a>

Exito. Todo se ha hecho de forma exitosa.
</div>

<div class="alert alert-block alert-warning">
<b>Comentario del revisor.</b> <a class="tocSkip"></a>

Observación. Algunas recomendaciones.
</div>

<div class="alert alert-block alert-danger">

<b>Comentario del revisor.</b> <a class="tocSkip"></a>

Necesita arreglos. Este apartado necesita algunas correcciones. El trabajo no puede ser aceptado con comentarios rojos. 
</div>

Puedes responder utilizando esto:

<div class="alert alert-block alert-info">
<b>Respuesta de estudiante.</b> <a class="tocSkip"></a>
</div>



Como parte del equipo de análisis, lo primero que debes hacer es evaluar la calidad de una muestra de datos recopilados y prepararla para analizarla posteriormente. Después, en la segunda parte de este proyecto en el segundo sprint, desarrollarás más tus habilidades y harás tu primer análisis completo, respondiendo a las necesidades del cliente.

Estos son los datos que el cliente nos proporcionó. Tienen el formato de una lista de Python, con las siguientes columnas de datos:

- **user_id:** Identificador único para cada usuario.
- **user_name:** El nombre del usuario.
- **user_age:** La edad del usuario.
- **fav_categories:** Categorías favoritas de los artículos que compró el usuario, como 'ELECTRONICS', 'SPORT' y 'BOOKS' (ELECTRÓNICOS, DEPORTES y LIBROS), etc.
- **total_spendings:** Una lista de números enteros que indican la cantidad total gastada en cada una de las categorías favoritas.

In [ ]:
users = [
    ['32415', ' mike_reed ', 32.0, ['ELECTRONICS', 'SPORT', 'BOOKS'], [894, 213, 173]],
    ['31980', 'kate morgan', 24.0, ['CLOTHES', 'BOOKS'], [439, 390]],
    ['32156', ' john doe ', 37.0, ['ELECTRONICS', 'HOME', 'FOOD'], [459, 120, 99]],
    ['32761', 'SAMANTHA SMITH', 29.0, ['CLOTHES', 'ELECTRONICS', 'BEAUTY'], [299, 679, 85]],
    ['32984', 'David White', 41.0, ['BOOKS', 'HOME', 'SPORT'], [234, 329, 243]],
    ['33001', 'emily brown', 26.0, ['BEAUTY', 'HOME', 'FOOD'], [213, 659, 79]],
    ['33767', ' Maria Garcia', 33.0, ['CLOTHES', 'FOOD', 'BEAUTY'], [499, 189, 63]],
    ['33912', 'JOSE MARTINEZ', 22.0, ['SPORT', 'ELECTRONICS', 'HOME'], [259, 549, 109]],
    ['34009', 'lisa wilson ', 35.0, ['HOME', 'BOOKS', 'CLOTHES'], [329, 189, 329]],
    ['34278', 'James Lee', 28.0, ['BEAUTY', 'CLOTHES', 'ELECTRONICS'], [189, 299, 579]],
]

# Paso 1

Store 1 tiene como objetivo garantizar la coherencia en la recopilación de datos. Como parte de esta iniciativa, se debe evaluar la calidad de los datos recopilados sobre los usuarios y las usuarias. Te han pedido que revises los datos recopilados y propongas cambios. A continuación verás datos sobre un usuario o una usuaria en particular; revisa los datos e identifica cualquier posible problema.

In [ ]:
user_id = '32415'
user_name = ' mike_reed '
user_age = 32.0
fav_categories = ['ELECTRONICS', 'SPORT', 'BOOKS']

**Opciones:**

1. Se debe cambiar el tipo de dato de `user_id` de cadena a entero.
    
2. La variable `user_name` contiene una cadena que tiene espacios innecesarios y un guion bajo entre el nombre y el apellido.
    
3. El tipo de dato de `user_age` es correcto y no hay necesidad de convertirlo.
    
4. La lista `fav_categories` contiene cadenas en mayúsculas. En lugar de ello, debemos convertir los valores de la lista en minúsculas.

Para cada una de las opciones, escribe en la siguiente celda markdown si la identificaste como un problema real en los datos o no. Justifica tu razonamiento. Por ejemplo, si crees que la primera opción es correcta, escríbelo y explica por qué piensas que es correcta.

**Escribe tu respuesta y explica tu argumentación:**

Opción 1. Pienso que al ser un identificador el tipo de dato str podría quedar bien tal cual está en esta variable al ser valores que no se ocuparán para hacer cálculos.

Opción 2. Los espacios innecesarios deberían quitarse así como el guión bajo que sustituye al espacio, no dan valor al dato.

Opción 3. El tipo de dato para la edad no es el más adecuado, ya que las edades normalmente se tratan como enteros, por lo que habría que convertir los valores a tipo int.

Opción 4. En base a la muestra de datos, todos los valores mostrados de las listas son consistentes por lo que dejarlos en mayúsculas, como vienen de origen, sería correcto.

<div class="alert alert-block alert-warning">
<b>Comentario del revisor Iteración 1.</b>

Has hecho un buen trabajo analizando cada situación. Aquí van algunas sugerencias:

1. Usar una cadena como identificador fue una elección acertada. Si decides cambiar a un número entero, asegúrate de que sea necesario en ese contexto.
2. Comprendiste bien la importancia de quitar espacios innecesarios. Considera si usar guiones bajos podría ayudarte a organizar mejor tus datos.
3. Elegir que la edad sea un número entero fue una decisión adecuada, ya que representa el dato de manera más precisa.
4. Aunque usar mayúsculas es consistente, te recomendaría optar por minúsculas por convención. No es un gran problema, así que sigue concentrándote en mejorar.
</div>

# Paso 2

Vamos a implementar los cambios que identificamos. Primero, necesitamos corregir los problemas de la variable `user_name` Como vimos, tiene espacios innecesarios y un guion bajo como separador entre el nombre y el apellido; tu objetivo es eliminar los espacios y luego reemplazar el guion bajo con el espacio.

In [4]:
user_name = ' mike_reed '
user_name = user_name.strip().replace('_', ' ')

print(user_name)

mike reed

********Hint********

Existe un método, `strip()`, que puede eliminar espacios al principio y al final de una cadena. Además, el método `replace()` se puede usar para reemplazar una parte de una cadena. En este caso, queremos reemplazar los guiones bajos (`_`) con espacios.

<div class="alert alert-block alert-success">
<b>Comentario del revisor Iteración 1.</b>

Hiciste un buen trabajo al cambiar 'mike_reed' por 'mike reed'. Utilizaste adecuadamente los métodos strip() y replace() para ajustar el texto. Sigue así.
</div>

# Paso 3

Luego, debemos dividir el `user_name` (nombre de usuario o usuaria) actualizado en dos subcadenas para obtener una lista que contenga dos valores: la cadena para el nombre y la cadena para el apellido.

In [5]:
user_name = 'mike reed'
name_split = user_name.split()

print(name_split)

['mike', 'reed']

********Hint********

El método `split()` se utiliza para dividir una cadena. Por defecto, utiliza un espacio como separador.

<div class="alert alert-block alert-success">
<b>Comentario del revisor Iteración 1.</b>

Buen trabajo. Has utilizado el método split() para separar la cadena, y ahora tienes una lista con tu nombre y apellido extraídos del texto original. No es necesario realizar más cambios.
</div>

# Paso 4

¡Genial! Ahora debemos trabajar con la variable `user_age`. Como ya mencionamos, esta tiene un tipo de datos incorrecto. Arreglemos este problema transformando el tipo de datos y mostrando el resultado final.

In [6]:
user_age = 32.0
user_age = int(user_age)

print(user_age)

32

********Hint********

¿Qué tipo de datos eliminará la parte de coma flotante?

<div class="alert alert-block alert-success">
<b>Comentario del revisor Iteración 1.</b>

Has hecho un buen trabajo al escribir tu código para convertir un número flotante en un entero eliminando la parte decimal. El resultado es correcto y cumple con lo solicitado. Sigue adelante.
</div>

# Paso 5

Como sabemos, los datos no siempre son perfectos. Debemos considerar escenarios en los que el valor de `user_age` no se pueda convertir en un número entero. Para evitar que nuestro sistema se bloquee, debemos tomar medidas con anticipación.

Escribe un código que intente convertir la variable `user_age` en un número entero y asigna el valor transformado a `user_age_int`. Si el intento falla, mostramos un mensaje pidiendo al usuario o la usuaria que proporcione su edad como un valor numérico con el mensaje: `Please provide your age as a numerical value.` (Proporcione su edad como un valor numérico.)

In [7]:
user_age = 'treinta y dos'

try:
    user_age_int = int(user_age)
except:
    print('Please provide your age as a numerical value.')

Please provide your age as a numerical value.

********Hint********

Utiliza un bloque `try-except` para intentar la conversión; si falla, proporciona un mensaje claro indicando que la entrada debe ser numérica.

<div class="alert alert-block alert-warning">
<b>Comentario del revisor Iteración 1.</b>

Has hecho un buen trabajo al convertir cadenas a números utilizando un bloque try-except y proporcionando un mensaje claro en caso de error. Para mejorar tu código, podrías especificar el tipo de error que esperas, como ValueError, lo que lo haría más preciso. También podrías imprimir el número convertido cuando todo salga bien para facilitar la verificación del resultado. Sigue así; vas por buen camino.
</div>

# Paso 6

El equipo de dirección de Store 1 te pidió ayudarles a organizar los datos de sus clientes para analizarlos y gestionarlos mejor.

Tu tarea es ordenar esta lista por ID de usuario de forma ascendente para que sea más fácil acceder a ella y analizarla.

In [8]:
users = [
    ['32415', ' mike_reed ', 32.0, ['ELECTRONICS', 'SPORT', 'BOOKS'], [894, 213, 173]],
    ['31980', 'kate morgan', 24.0, ['CLOTHES', 'BOOKS'], [439, 390]],
    ['32156', ' john doe ', 37.0, ['ELECTRONICS', 'HOME', 'FOOD'], [459, 120, 99]],
    ['32761', 'SAMANTHA SMITH', 29.0, ['CLOTHES', 'ELECTRONICS', 'BEAUTY'], [299, 679, 85]],
    ['32984', 'David White', 41.0, ['BOOKS', 'HOME', 'SPORT'], [234, 329, 243]],
    ['33001', 'emily brown', 26.0, ['BEAUTY', 'HOME', 'FOOD'], [213, 659, 79]],
    ['33767', ' Maria Garcia', 33.0, ['CLOTHES', 'FOOD', 'BEAUTY'], [499, 189, 63]],
    ['33912', 'JOSE MARTINEZ', 22.0, ['SPORT', 'ELECTRONICS', 'HOME'], [259, 549, 109]],
    ['34009', 'lisa wilson ', 35.0, ['HOME', 'BOOKS', 'CLOTHES'], [329, 189, 329]],
    ['34278', 'James Lee', 28.0, ['BEAUTY', 'CLOTHES', 'ELECTRONICS'], [189, 299, 579]],
]

users.sort()

print(users)

[['31980', 'kate morgan', 24.0, ['CLOTHES', 'BOOKS'], [439, 390]], ['32156', ' john doe ', 37.0, ['ELECTRONICS', 'HOME', 'FOOD'], [459, 120, 99]], ['32415', ' mike_reed ', 32.0, ['ELECTRONICS', 'SPORT', 'BOOKS'], [894, 213, 173]], ['32761', 'SAMANTHA SMITH', 29.0, ['CLOTHES', 'ELECTRONICS', 'BEAUTY'], [299, 679, 85]], ['32984', 'David White', 41.0, ['BOOKS', 'HOME', 'SPORT'], [234, 329, 243]], ['33001', 'emily brown', 26.0, ['BEAUTY', 'HOME', 'FOOD'], [213, 659, 79]], ['33767', ' Maria Garcia', 33.0, ['CLOTHES', 'FOOD', 'BEAUTY'], [499, 189, 63]], ['33912', 'JOSE MARTINEZ', 22.0, ['SPORT', 'ELECTRONICS', 'HOME'], [259, 549, 109]], ['34009', 'lisa wilson ', 35.0, ['HOME', 'BOOKS', 'CLOTHES'], [329, 189, 329]], ['34278', 'James Lee', 28.0, ['BEAUTY', 'CLOTHES', 'ELECTRONICS'], [189, 299, 579]]]

********Hint********

Puedes utilizar el método `sort()` en la lista de usuarios para ordenarla de forma ascendente.

<div class="alert alert-block alert-success">
<b>Comentario del revisor Iteración 1.</b>

Has organizado tu lista de usuarios en orden ascendente utilizando el método `sort()`. El resultado es correcto y cumple con lo solicitado. ¡Buen trabajo!
</div>

# Paso 7

Tenemos la información de los hábitos de consumo de nuestros usuarios, incluyendo la cantidad gastada en cada una de sus categorías favoritas. La dirección está interesada en conocer la cantidad total gastada por el usuario.


Calculemos este valor y despleguémoslo.

In [13]:
fav_categories_low = ['electronics', 'sport', 'books']
spendings_per_category = [894, 213, 173]

total_amount = sum(spendings_per_category)
#El método sum() no se tocó en la teoría pero busque sobre ello en internet
#Revise también sobre min() y max() ya que la pista de abajo mecionan estos métodos

print(total_amount)

1280

********Hint********

¿Cuáles son los tres métodos que se pueden aplicar a una lista para calcular sus valores mínimo, máximo y total?

<div class="alert alert-block alert-success">
<b>Comentario del revisor Iteración 1.</b>

Hiciste un buen trabajo al calcular la suma de tus gastos por categoría utilizando la función sum(). Además, investigaste por tu cuenta sobre las funciones min() y max(), lo cual es excelente para continuar aprendiendo. El resultado de tu código es correcto y no requiere ajustes. Sigue adelante.
</div>

# Paso 8

La dirección de la empresa nos pidió pensar en una manera de resumir toda la información de un usuario. Tu objetivo es crear una cadena formateada que utilice información de las variables `user_id`, `user_name` y `user_age`.

Esta es la cadena final que queremos crear: `User 32415 is mike who is 32 years old.` (El usuario 32415 es Mike, quien tiene 32 años).

In [14]:
user_id = '32415'
user_name = ['mike', 'reed']
user_age = 32

user_info = f"User {user_id} is {user_name[0]} who is {user_age} years old."
print(user_info)

User 32415 is mike who is 32 years old.

********Hint********

Para crear una cadena, puedes utilizar el método `format()` o f-string. Para extraer el nombre de la lista `user_name`, puedes utilizar la segmentación.

<div class="alert alert-block alert-success">
<b>Comentario del revisor Iteración 1.</b>

Tu código está bien realizado y cumple con lo solicitado. Elegiste usar f-strings para formatear las cadenas, lo cual es una manera clara y sencilla de hacerlo. El resultado es preciso y cumple con las expectativas. ¡Buen trabajo!
</div>

# Paso 9

La dirección también quiere una forma fácil de conocer la cantidad de clientes con cuyos datos contamos. Tu objetivo es crear una cadena formateada que muestre la cantidad de datos de clientes registrados.

Esta es la cadena final que queremos crear: `Hemos registrado datos de X clientes`.

In [15]:
users = [
    ['32415', ' mike_reed ', 32.0, ['ELECTRONICS', 'SPORT', 'BOOKS'], [894, 213, 173]],
    ['31980', 'kate morgan', 24.0, ['CLOTHES', 'BOOKS'], [439, 390]],
    ['32156', ' john doe ', 37.0, ['ELECTRONICS', 'HOME', 'FOOD'], [459, 120, 99]],
    ['32761', 'SAMANTHA SMITH', 29.0, ['CLOTHES', 'ELECTRONICS', 'BEAUTY'], [299, 679, 85]],
    ['32984', 'David White', 41.0, ['BOOKS', 'HOME', 'SPORT'], [234, 329, 243]],
    ['33001', 'emily brown', 26.0, ['BEAUTY', 'HOME', 'FOOD'], [213, 659, 79]],
    ['33767', ' Maria Garcia', 33.0, ['CLOTHES', 'FOOD', 'BEAUTY'], [499, 189, 63]],
    ['33912', 'JOSE MARTINEZ', 22.0, ['SPORT', 'ELECTRONICS', 'HOME'], [259, 549, 109]],
    ['34009', 'lisa wilson ', 35.0, ['HOME', 'BOOKS', 'CLOTHES'], [329, 189, 329]],
    ['34278', 'James Lee', 28.0, ['BEAUTY', 'CLOTHES', 'ELECTRONICS'], [189, 299, 579]],
]


user_info = f"We have registered data on {len(users)} clients."
print(user_info)

We have registered data on 10 clients.

********Hint********

Para crear una cadena, puedes utilizar el método `format()` o f-string. Para extraer la cantidad de clientes en la lista, puedes utilizar la función que devuelve la longitud de la lista.

<div class="alert alert-block alert-success">
<b>Comentario del revisor Iteración 1.</b>

Has seguido las instrucciones de manera efectiva para crear una cadena que muestra la cantidad de clientes registrados utilizando la función len() y una f-string. Aunque el mensaje está en inglés, cumple con lo solicitado. ¡Buen trabajo!
</div>

# Paso 10

Apliquemos ahora todos los cambios a la lista de clientes. Para simplificar las cosas, te proporcionaremos una más corta.
Debes:
1. Eliminar todos los espacios iniciales y finales de los nombres, así como cualquier guion bajo.
2. Convertir todas las edades en números enteros.
3. Separar todos los nombres y apellidos en una sublista.

Guarda la lista modificada como una nueva lista llamada `users_clean` y muéstrala en la pantalla.

In [22]:
users = [
    ['32415', ' mike_reed ', 32.0, ['ELECTRONICS', 'SPORT', 'BOOKS'], [894, 213, 173]],
    ['31980', 'kate morgan', 24.0, ['CLOTHES', 'BOOKS'], [439, 390]],
    ['32156', ' john doe ', 37.0, ['ELECTRONICS', 'HOME', 'FOOD'], [459, 120, 99]],
]

users_clean = []
user_data_1 = []
user_data_2 = []
user_data_3 = []


# Procesa al primer usuario
user_id_1 = users[0][0]
user_name_1 = users[0][1].strip().replace('_', ' ')
user_age_1 = int(users[0][2])
user_data_1.extend([user_id_1, user_name_1, user_age_1, users[0][3], users[0][4]])

# Procesa al segundo usuario
user_id_2 = users[1][0]
user_name_2 = users[1][1].strip().replace('_', ' ')
user_age_2 = int(users[1][2])
user_data_2.extend([user_id_2, user_name_2, user_age_2, users[1][3], users[1][4]])

# Procesa al tercer usuario
user_id_3 = users[2][0]
user_name_3 = users[2][1].strip().replace('_', ' ')
user_age_3 = int(users[2][2])
user_data_3.extend([user_id_3, user_name_3, user_age_3, users[2][3], users[2][4]])

users_clean.extend([user_data_1, user_data_2, user_data_3])

print(users_clean)

[['32415', 'mike reed', 32, ['ELECTRONICS', 'SPORT', 'BOOKS'], [894, 213, 173]], ['31980', 'kate morgan', 24, ['CLOTHES', 'BOOKS'], [439, 390]], ['32156', 'john doe', 37, ['ELECTRONICS', 'HOME', 'FOOD'], [459, 120, 99]]]

********Hint********

Para procesar a cada usuario, comienza por acceder a los elementos requeridos de la lista de usuarios. Utiliza el método `strip()` para eliminar los espacios iniciales y finales y el método `replace('_',' ')` para reemplazar los guiones bajos por espacios en los nombres. Convierte la edad a un número entero utilizando `int()`. Separa el nombre completo en nombre y apellido utilizando el método `split()`. Por último, `append` (agrega) los datos limpios a la lista `users_clean`.

----------

<div class="alert alert-block alert-warning">
<b>Comentario del revisor Iteración 1.</b>

Tu código realiza un buen trabajo en el procesamiento de datos y genera resultados útiles. Una sugerencia para mejorarlo sería considerar la separación del nombre y el apellido en una lista, en lugar de tenerlos juntos como una sola cadena. Esto es más una cuestión de estilo y no afecta el funcionamiento del código, pero podría hacerlo más consistente con las estructuras recomendadas. Utilizar el método split() para dividir el nombre y el apellido podría alinear tu trabajo con las mejores prácticas.
</div>